const FlatApi = [
 {
    id: 1,
    Image: './assets/img1.jpg',
    Image1: './assets/img1.jpg',
    project: 'Sunrise park',
    name: 'lodha',
    location: 'Mumbai',
    subLocation: 'Mulund',
    size: '2 BHK',
    size1: '4 BHK',
    describe: 'RTM', 
    area: '350 sqft',
    price: 3.75,
    priceRange: 'crore',
    p1: 'lorem abcd',
    p2: 'lorem lmno',
    p3: 'lorem xyz',
 },
 {
   id: 2,
   Image: './assets/krishna1.jpg',
   Image1: './assets/krishna1.jpg',
   project: 'Cyprus',
   name: 'L&T',
   location: 'Mumbai',
   subLocation: 'Bhandup',
   size: '1 BHK',
   size1: '3 BHK',
   describe: 'RTM', 
   area: '350 sqft',
   price: 99,
   priceRange: 'lakh',
   p1: 'lorem abcd',
   p2: 'lorem lmno',
   p3: 'lorem xyz',  
},
 {
   id: 3,
   Image: './assets/img1.jpg',
   Image1: './assets/img1.jpg',
   project: 'Sealink',
   name: 'L&T',
   location: 'Mumbai',
   subLocation: 'Ghatkopar',
   size: '3 BHK',
   size1: '5 BHK',
   describe: 'RTM', 
   area: '350 sqft',
   price: 4.4,
   priceRange: 'crore',
   p1: 'lorem abcd',
   p2: 'lorem lmno',
   p3: 'lorem xyz',
},
{
   id: 4,
   Image: './assets/img1.jpg',
   Image1: './assets/img1.jpg',
   project: 'Skyline',
   name: 'Oberoi',
   location: 'Mumbai',
   subLocation: 'Nahur',
   size: '3 BHK',
   size1: '1 BHK',
   describe: 'RTM', 
   area: '670 sqft',
   price: 5.5,
   priceRange: 'crore',
   p1: 'lorem abcd',
   p2: 'lorem lmno',
   p3: 'lorem xyz',
},
{
  id: 5,
  Image: './assets/krishna1.jpg',
  Image1: './assets/krishna1.jpg',
  project: 'Adventure',
  name: 'Mahindra',
  location: 'Mumbai',
  subLocation: 'Bhandup',
  size: '1 BHK',
  size1: '3 BHK',
  describe: 'RTM', 
  area: '350 sqft',
  price: 1.15,
  priceRange: 'crore',
  p1: 'lorem abcd',
  p2: 'lorem lmno',
  p3: 'lorem xyz',  
},
{
  id: 6,
  Image: './assets/img1.jpg',
  Image1: './assets/img1.jpg',
  project: 'Seashore View',
  name: 'Tata',
  location: 'Mumbai',
  subLocation: 'Ghatkopar',
  size: '3 BHK',
  size1: '5 BHK',
  describe: 'RTM', 
  area: '350 sqft',
  price: 4.4,
  priceRange: 'crore',
  p1: 'lorem abcd',
  p2: 'lorem lmno',
  p3: 'lorem xyz',
},

 {
    id: 7,
    Image: './assets/krishna1.jpg',
    Image1: './assets/krishna1.jpg',
    project: 'sunset',
    name: 'krishna',
    location: 'Pune',
    subLocation: 'Baramati',
    size: '1 BHK',
    size1: '',
    describe: 'UC',
    area: '400 sqft',
    price: 45.49,
    priceRange: 'lakh',
    p1: 'lorem abcd',
    p2: 'lorem lmno',
    p3: 'lorem xyz',   
 },

 {
   id: 8,
   Image: './assets/img1.jpg',
   Image1: './assets/img1.jpg',
   project: 'Starfish',
   name: 'L&T',
   location: 'Thane',
   subLocation: 'Ghodbunder',
   size: '3 BHK',
   size1: '5 BHK',
   describe: 'RTM', 
   area: '350 sqft',
   price: 4.4,
   priceRange: 'crore',
   p1: 'lorem abcd',
   p2: 'lorem lmno',
   p3: 'lorem xyz',
},
 

 {
   id: 9,
   Image: './assets/img1.jpg',
   Image1: './assets/img1.jpg',
   project: 'Runwal Green',
   name: 'runwal',
   location: 'Thane',
   subLocation: 'Kopri',
   size: '3 BHK',
   size1: '',
   describe: 'UC',
   area: '600 sqft',
   price: 2.3,
   priceRange: 'crore',
   p1: 'lorem abcd',
   p2: 'lorem lmno',
   p3: 'lorem xyz',
 },


];

export default FlatApi